### ISSUE TITLE
Exemple for controlling the vehicle

### ISSUE THREAD

**Issue by TheGreatLebowski** [uuvsimulator/uuv_simulator#384]
Hello,

In the section _Configuring the thruster manager_ of the tutorial, it is written at the end 

> To command the vehicle, you have to start the thruster manager and publish a ROS Wrench message to the input topic /<ROBOT_NAME or ROBOT_NAMESPACE>/thruster_manager/input with the wrench command to the vehicle.

Can you add an example ? And also I don't understand where I should put the command ...

Thank you for your help !

**Comment by TheGreatLebowski** [comment]
I've maybe found an example but he is not working :

```
rostopic pub /submarine/thrusters/0/thrust_wrench geometry/WrenchStamped "header:
seq: 0
stamp:
  secs: 0
  nsecs: 0
frame_id=''
wrench:
  force:
    x: value
    y: value
    z: value
  torque:
    x: value
    y: value
    z: value"
```

But this error appears : 

> /opt/melodic/lib/python2.7/dist-packages/rostopic/__init__.py:1782: TAMLLoad Warning: calling yaml.load() without Loader=... is deprecated, as the default to Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
>  pub_args.append(yaml.load(arg))
> publishing and latching message. 

https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

A solution is available on this link, but doesn't work on my machine ...

Is my example wrong ? Or there is a bug ?
