### ISSUE TITLE
Problem while trying to control the robot to some waypoint

### ISSUE THREAD

**Issue by luym11** [uuvsimulator/uuv_simulator#80]
Hi! 

Firstly I have a world, a rov and a correspoding dp_controller running and I want to control the rov to a waypoint through terminal commands. I searched the topic list and the service list, found one service that I guess might help. So I tried 
```

rosservice call /rexrov2/go_to "waypoint:
  point:
    x: 0.0
    y: 20.0
    z: 0.0
  max_forward_speed: 1.0
  heading_offset: 0.0
  use_fixed_heading: false" 
```
But it gave me error message as
`ERROR: service [/rexrov2/go_to] responded with an error: error processing request: global name 'i' is not defined`

Could you please kindly advice how should I solve this? Or could you please suggest a better way to control waypoints through sending commands? (different from the tutorial, in which the program reads waypoints from yaml file)

Thank you! 

Yimeng
